### ISSUE TITLE
Document deploy of OpenShift Container Storage (OCS)

### ISSUE THREAD

**Issue by liveaverage** [RedHatSI/openshift-packet-deploy#33]
This would help with #22, particularly with consideration of VM live migration when running CNV, and provide an integrated s3 endpoint for OCP tenants. Couple of notes:

- only applies to worker count >= 3
- requires a few extra steps to enable/subscribe to the operator
- might require custom configuration for supplemental storage on worker nodes

operator subscription manifest (and prereqs for singleNamespace deployment):
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-operatorgroup
  namespace: openshift-storage
spec:
  serviceAccount:
    metadata:
      creationTimestamp: null
  targetNamespaces:
  - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  channel: stable-4.3
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ocs-operator.v4.3.0
```
